/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BlogService } from "../blog.service";
import { BlogCreateInput } from "./BlogCreateInput";
import { Blog } from "./Blog";
import { BlogFindManyArgs } from "./BlogFindManyArgs";
import { BlogWhereUniqueInput } from "./BlogWhereUniqueInput";
import { BlogUpdateInput } from "./BlogUpdateInput";
import { BlogEventFindManyArgs } from "../../blogEvent/base/BlogEventFindManyArgs";
import { BlogEvent } from "../../blogEvent/base/BlogEvent";
import { BlogEventWhereUniqueInput } from "../../blogEvent/base/BlogEventWhereUniqueInput";

export class BlogControllerBase {
  constructor(protected readonly service: BlogService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Blog })
  async createBlog(@common.Body() data: BlogCreateInput): Promise<Blog> {
    return await this.service.createBlog({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Blog] })
  @ApiNestedQuery(BlogFindManyArgs)
  async blogs(@common.Req() request: Request): Promise<Blog[]> {
    const args = plainToClass(BlogFindManyArgs, request.query);
    return this.service.blogs({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Blog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async blog(
    @common.Param() params: BlogWhereUniqueInput
  ): Promise<Blog | null> {
    const result = await this.service.blog({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Blog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateBlog(
    @common.Param() params: BlogWhereUniqueInput,
    @common.Body() data: BlogUpdateInput
  ): Promise<Blog | null> {
    try {
      return await this.service.updateBlog({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Blog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBlog(
    @common.Param() params: BlogWhereUniqueInput
  ): Promise<Blog | null> {
    try {
      return await this.service.deleteBlog({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/blogEvents")
  @ApiNestedQuery(BlogEventFindManyArgs)
  async findBlogEvents(
    @common.Req() request: Request,
    @common.Param() params: BlogWhereUniqueInput
  ): Promise<BlogEvent[]> {
    const query = plainToClass(BlogEventFindManyArgs, request.query);
    const results = await this.service.findBlogEvents(params.id, {
      ...query,
      select: {
        blog: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/blogEvents")
  async connectBlogEvents(
    @common.Param() params: BlogWhereUniqueInput,
    @common.Body() body: BlogEventWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      blogEvents: {
        connect: body,
      },
    };
    await this.service.updateBlog({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/blogEvents")
  async updateBlogEvents(
    @common.Param() params: BlogWhereUniqueInput,
    @common.Body() body: BlogEventWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      blogEvents: {
        set: body,
      },
    };
    await this.service.updateBlog({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/blogEvents")
  async disconnectBlogEvents(
    @common.Param() params: BlogWhereUniqueInput,
    @common.Body() body: BlogEventWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      blogEvents: {
        disconnect: body,
      },
    };
    await this.service.updateBlog({
      where: params,
      data,
      select: { id: true },
    });
  }
}
